### ISSUE TITLE
Example Usage?

### ISSUE THREAD

**Issue by mr-feek** [ndianabasi/adonis-drive-r2#1]
Hi, first off thanks for the package!

# Ask
Could you please provide an example for how to use this package properly when uploading a file?

# Problem
I am attempting to define an r2 `disk` with multiple different `buckets` depending on my business logic. So I have one r2 disk defined in my `drive.ts` file.

In my file upload route, I am trying to define the `bucket` to use at runtime via utilizing the first parameter of `file.moveToDisk(bucket, options, 'r2'`), however this prefixes the cloudflare url with the global config bucket name (dummyBucket). 

For example, this code generates the following:

```
drive.ts

r2: {
            driver: 'r2',
            visibility: 'private',
            key: Env.get('R2_ACCESS_KEY_ID'),
            secret: Env.get('R2_SECRET_ACCESS_KEY'),
            bucket: Env.get('R2_BUCKET'),
            accountId: Env.get('R2_ACCOUNT_ID'),
            cdnUrl: Env.get('R2_PUBLIC_URL')
        }
```
```
.env

R2_ACCESS_KEY_ID=[redacted]
R2_SECRET_ACCESS_KEY=[redacted]
R2_ACCOUNT_ID=[redacted]
R2_BUCKET=dummyBucket
R2_PUBLIC_URL=[redacted]
```

```
file upload logic

public async saveUpload(
        user: User,
        file: MultipartFileContract,
        diskName: keyof DisksList,
        bucketName: string,
        options: {},
    ) {
        await file.moveToDisk(bucketName, options, diskName);
```

when i throw in a debugger to my exception handler and examine the `error.orginal.$response.body.req._header`, i see something like 

`PUT /dummyBucket/{first param of file.moveToDisk}/[redacted]?x-id=PutObject HTTP/1.1`

Is that intentional? Should I not be trying to define the bucket at runtime, and instead define multiple "r2" disks for each bucket? 

I'm extremely new to adonis and r2, but i was imagining the url would end up looking like `PUT /{first param of file.moveToDisk/[redacted]}`, and I _think_ that's what r2 is expecting.

Thanks for any input!

**Comment by ndianabasi** [comment]
Hi @mr-feek. Please provide more information like:

- Your config in `config/drive.ts`,
- What you expect the URL to be,
- The current URL generated by the package.

**Comment by mr-feek** [comment]
sorry just edited!

**Comment by ndianabasi** [comment]
The first parameter of `moveToDisk` is the `storagePath` which is a relative path to the disk root (in your case, the bucket). You are basically supplying the bucket name twice.

Use this instead:

`await file.moveToDisk('./', options, diskName);`

**Comment by mr-feek** [comment]
@ndianabasi is there a way to define bucket at runtime, so that I can switch buckets depending my business logic? I was hoping that is what I could accomplish via the first parameter of `moveToDisk`. 

I see there is a `bucket` method exposed by this driver which I assume does what I want, however that method won't work for the `local` driver, messing with local development :/ I would prefer not to fork logic based on the driver. Thoughts?

**Comment by ndianabasi** [comment]
If you use the `r2` driver with either https://www.npmjs.com/package/adonis-responsive-attachment or https://github.com/adonisjs/attachment-lite, you can set the bucket at runtime.

**Comment by mr-feek** [comment]
Cool, I'll take a look at that. Thank you for this package and your quick response!! I super appreciate it 🤝

**Comment by mr-feek** [comment]
in case someone else runs into this in the future, I implemented a hack like this:

```
public async saveUpload(
        user: User,
        file: MultipartFileContract,
        diskName: keyof DisksList,
        bucketName: string,
        options: {},
    ) {
        const driver = Drive.use(diskName);

        // @see https://github.com/adonisjs/bodyparser/blob/efeb2a57e2773e18f3aa27fcfe4d0609ab0b947f/src/Multipart/File.ts#L210
        // we are essentially re-implementing `file.moveToDisk`, as moveToDisk does not allow changing bucket at runtime
        Object.assign(options, {
            contentType: `${file.type}/${file.subtype}`,
            contentLength: file.size,
        });

        const key = `${user.id}.${cuid()}.${file.extname}`;

        if ('bucket' in driver) {
            await driver.bucket(bucketName).putStream(key, fs.createReadStream(file.tmpPath!), options);
        } else {
            // why does this hack exist? Well our production r2 driver has/needs a `bucket` method, but the default local + fake drivers in adonis don't have this method. 
            await driver.putStream(bucketName + '/' + key, fs.createReadStream(file.tmpPath!), options);
        }

        file.markAsMoved(key, await driver.getUrl(key));
}
```
